- backend/testData/Tracks.sql
- backend/testData/users.sql
*database table for tracks created
*this is just a initial schema.we will add,update and edit in future
> data base tracks created

- backend/testData/playlists.sql
*database table for playlists created
*this is just a initial schema.we will add,update and edit in future
> database playlist table created

- frontend/src/App.js
- frontend/src/components/Footer.jsx
* Create a footer and make it work
* Remove header tag wrapping the RouterProvide because the RouterProvider gives access to the main content (RouterProvider does not function as a navigation)
> Create a footer component  and fix a tiny bug in App.js

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/AppRouter.jsx
- frontend/src/components/SharePlaylistInputBox.jsx
- frontend/src/components/screens/MainScreen.jsx
- frontend/src/components/screens/PlaylistTracksScreen.jsx
* Add a screen for Junita to display tracks of a single playlist
* Connect the tracks display page with the "Add" button under the input box
* Fix footer problem so that it sticks at the bottom of the page
> Add single playlist tracks screen for Junita to display tracks of a single playlist

- frontend/src/components/dialogs/PlaylistTracksFilterModal.jsx
- frontend/src/components/screens/LoginScreen.jsx
- frontend/src/components/screens/PlaylistTracksScreen.jsx
- frontend/src/index.css
* Create a modal on the page http://localhost:3000/app/playlist using headlessui library
* When the "Filter by" button is clicked on http://localhost:3000/app/playlist page, it will pop up the modal on top of that page
* Do very basic styling so that group members can style it according to the design
* Team members will need to run "npm install"
> Create a modal that will hold the filter components to filter the tracks

- frontend/src/components/SharedPlaylistDisplay.jsx
*added genre
*added duration as a lenght
*formatted ms to minute for duration
*added image for single track
> track display updated with genre, length and track images

- frontend/src/utils/Auth.js
we created the Auth file because we wanted to have a single place for authentication.
> added the Auth file

- frontend/src/AppRouter.jsx
- frontend/src/components/CheckAuthenication.jsx
*created checkauthenication component to see user is logged in or not and to navigate them to diffrent pages according to their log in status
* connected it to app router
> created checkauthenication component

- frontend/src/AppRouter.jsx
- frontend/src/components/DynamicGenres.jsx
- frontend/src/components/SharePlaylistInputBox.jsx
- frontend/src/components/SharedPlaylistDisplay.jsx
- frontend/src/components/screens/MainScreen.jsx
- frontend/src/components/screens/PlaylistTracksScreen.jsx
displaying all traks from playlist and filter them by genre
> shared playlist in tracksScreen

- frontend/src/components/Header.jsx
- frontend/src/components/Playlists.jsx
- frontend/src/components/SharePlaylistInputBox.jsx
- frontend/src/components/screens/MainScreen.jsx
* Incorporate the recent design changes according to the design suggested by our UX/UI designer
* Make the page responsive using Tailwind
* Make it more semantic by replacing h1 with p tags as h1 is for titles for the convenience of screen readers
* Remove unnecessary div tags
I hope you like this 
Mobile version
Tablet version
Desktop version
> Style the authenticated homepage using Tailwind

- frontend/src/components/screens/LoginScreen.jsx
- frontend/src/utils/spotifyApiUtils.js
* We do this so that we are not redirected to our localhost when we are in https://song-sieve-frontend.onrender.com/
> Fix the bug to redirect the page to current page

- frontend/src/AppRouter.jsx
- frontend/src/components/Playlists.jsx
- frontend/src/components/SharePlaylistInputBox.jsx
- frontend/src/components/SharedPlaylistDisplay.jsx
- frontend/src/components/screens/FilteredTracksScreen.jsx
- frontend/src/components/screens/MainScreen.jsx
- frontend/src/index.css
one component( <FilteredTracksScreen/> ) was created to display filtered tracks
> created the page for displaying filtered tracks on it

- frontend/src/components/ContentCheckBox.jsx
- frontend/src/components/dialogs/PlaylistTracksFilterModal.jsx
* 2 checkboxes with option yes and no created to filtered tracks by content.eg if they are explicit or not
* ContentCheckBox imported to PlaylistTracksModal component to show it in filter by modal
> Feature - content check box

- frontend/src/App.js
- frontend/src/AppRouter.jsx
- frontend/src/components/Footer.jsx
- frontend/src/components/Header.jsx
- frontend/src/components/SharedPlaylistDisplay.jsx
- frontend/src/components/screens/FilteredTracksScreen.jsx
- frontend/src/index.css
i fixed bug related to footer and header
> Fixing header and footer css

- frontend/src/components/ContentCheckBox.jsx
- frontend/src/components/dialogs/PlaylistTracksFilterModal.jsx
* checkbox component update 
* imported checkbox componet in playlist modal to filter tracks by content(if they are explicit ot not)
> Feature content filter

- frontend/src/AppRouter.jsx
- frontend/src/components/ReccommendationPageLink.jsx
- frontend/src/components/screens/MainScreen.jsx
- frontend/src/components/screens/ReccommendationScreen.jsx
- frontend/src/index.css
*ReccommendationPageLink component created to navigate to recommendation page
*Reccommendation screen page created to display reccommendation list
*New path app/reccommendation added to app router
*sytling added
> Feature -navigation to recommendation page

- frontend/src/components/screens/MainScreen.jsx
* In the MainScreen add "accessToken" as the dependency in the second useEffect
> Fix the bug to display the playlists without clicking refresh button

- frontend/src/components/DurationFilter.jsx
- frontend/src/components/dialogs/PlaylistTracksFilterModal.jsx
- frontend/src/components/screens/MainScreen.jsx
- frontend/src/config.js
this pull request contains changes in 3 components
1-DurationFilters
2-PlaylistTracksFilterModal
3-MainScreen
> finished the filtered duration

- frontend/src/components/CyfRecommendation.jsx
- frontend/src/components/screens/ReccommendationScreen.jsx
- frontend/src/index.css
*cyf recommendation component created to display track list from track endpoint from backend
*added simple styling to start
> Feature - display recommendation track list

- frontend/src/components/Header.jsx
- frontend/src/components/LogOut.jsx
- frontend/src/index.css
* log out button added to take user back to log in page
> Feature log out

- backend/testData/cyf_tracks.json
- backend/testData/schema.sql
* Add iframe and image URL  columns to the tracks table in the database and update the tracks table in schema
* Add the updated json data in tracks file
* Edit previous member's favourite song
* Add new recommendations from CYF member
* Test the database on POSTMAN
* It is working on POSTMAN :+1:
> Change the files according to the recent changes in the database

- frontend/src/utils/encodingUtils.js
> docs: Added some docs for a test

- frontend/src/AppRouter.jsx
- frontend/src/components/CheckAuthenication.jsx
- frontend/src/config.js
- frontend/src/utils/Auth.js
*created checkauthenication component to see user is logged in or not and to navigate them to diffrent pages according to their log in status.
*connected it to app router
> Feature check authenication

- frontend/src/AppRouter.jsx
- frontend/src/components/CheckIfLoggedIn.jsx
- frontend/src/components/LogOut.jsx
- frontend/src/components/screens/MainScreen.jsx
- frontend/src/components/screens/SetToken.jsx
- frontend/src/config.js
- frontend/src/utils/Auth.js
* Break the component of MainScreen
* Set token component to store our access_token
* We did this together with our tech lead, Oliver
* We tested and everything is working :+1:
> Refactor authentication routing

- frontend/src/components/DynamicGenres.jsx
- frontend/src/components/dialogs/PlaylistTracksFilterModal.jsx
- frontend/src/components/screens/PlaylistTracksScreen.jsx
* Simplify the code to make the two filters function work
> Make the duration and content type work

- frontend/src/config.js
- frontend/src/index.js
Here is the source: https://reactrouter.com/en/main/routers/create-browser-router
> Fix bug related to routing

- frontend/src/components/screens/LoginScreen.jsx
- frontend/src/components/screens/SetToken.jsx
- frontend/src/config.js
- frontend/src/decideRedirectUrl.js
- frontend/src/utils/spotifyApiUtils.js
* fixed the re direct ulr which was not dynamic
closes #120
> fixed #120

- frontend/src/components/SharedPlaylistDisplay.jsx
- frontend/src/index.css
> changed tracks style

- frontend/src/components/LogOut.jsx
- frontend/src/index.css
> sign-out button styled

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/RecommendationPageLink.jsx
> gave motion to recommendation link

- backend/testData/schema.sql
- frontend/src/components/screens/LoginScreen.jsx
* Update the database with new CYF recommendations
* Made the Login page footer stick at the bottom
Closes#151
> Update database and fix footer bug

- frontend/src/components/screens/LoginScreen.jsx
- frontend/src/index.css
- Add the credentials of a dummy Spotify account to the login screen
- Add an alert box with the login info
> Help the testers login to our app

- frontend/public/index.html
* Change the title "React App" to something more specific to the app we created such as "Spotify Playlist Sieve"
* Remove unnecessary comments
> Change the title
